fix: missing Elasticsearch host during collectstatic
When collecting static assets outside of a working production deployment, the
Elasticsearch host is not available. This causes the `collectstatic` management
command to fail with:

  File "/openedx/richie/src/richie/apps/search/__init__.py", line 13, in <module>
    [getattr(settings, "RICHIE_ES_HOST", "elasticsearch")]
  File "/openedx/richie/src/richie/apps/search/elasticsearch.py", line 29, in __init__
    self.__es_version__ = self.info()["version"]["number"][:1]
  File "/openedx/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 101, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/openedx/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 265, in info
    return self.transport.perform_request("GET", "/", params=params)
  File "/openedx/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 409, in perform_request
    timeout=timeout,
  File "/openedx/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 245, in perform_request
    raise ConnectionError("N/A", str(e), e)
  elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd891758e50>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd891758e50>: Failed to establish a new connection: [Errno -2] Name or service not known)

To resolve this issue, we make sure that the
ElasticsearchClientCompat7to6.__es_version__ attribute is only set at runtime.